import Comments from "../comments";
function PrimeirosCOmputadores(props:any) {

  return (
    <>
      <div className="text-justify flex items-center flex-col mt-11 w-[90%] m-auto 2xl:w-[60%] xl:w-[60%]"> 
      
      <h1 className="text-2xl m-9">Os Primeiros Computadores</h1>
    <h2>Abaco o Inicio de tudo</h2>
<p><strong>A humanidade se desenvolveu usando muitas formas diferentes para calcular, primeiramente usava-se as m&atilde;os, usando os dedos como refer&ecirc;ncia, ent&atilde;o quando os dedos n&atilde;o eram suficiente passou a usar galhos, pedras e outros elementos, antes mesmo da escrita ser difundida e conhecida por todo o mundo, assim se deu&nbsp; uma inven&ccedil;&atilde;o, o &Aacute;baco, um instrumento b&aacute;sico de soma que se mostrou um auxiliar se c&aacute;lculos important&iacute;ssimo que surgiu por volta de 5500 A.C .</strong></p>
<img className="m-4" src="https://media.gettyimages.com/id/1972664444/pt/vetorial/old-chinese-abacus-wood-engraving-published-in-1869.jpg?s=612x612&w=gi&k=20&c=IXdU95xE9ZHAiPZ1m7fHE1EEEW8CpTStm_Jq1wvUVws=" alt="abaco img" />
<p><strong>Apesar de ser um grande passo ainda longe de chegar na era dos computadores, os &aacute;bacos eram manuais e precisavam de conhecimento para fazer subtra&ccedil;&atilde;o, soma, multiplica&ccedil;&atilde;o&nbsp; e divis&atilde;o.</strong></p>
<p><strong>Como o avan&ccedil;o da escrita agora de forma mundial, com a cultura de ler e escrever novos m&eacute;todos de c&aacute;lculos por meio de papel foram criados, mas eram matem&aacute;ticas que necessitavam de um conhecimento espec&iacute;fico ainda, o que demandava muito tempo e muito esfor&ccedil;o, assim se deu a necessidade do ser humano criar ferramentas e m&aacute;quinas para resolver essa quest&atilde;o de forma mais f&aacute;ceis.</strong></p>
<h3>Pascalina</h3>
<img className="m-4" src="https://www.computinghistory.org.uk/userdata/images/large/51/66/product-135166.jpg" alt="pascalina img" />
<p><strong>Agora chegando em tempos mais modernos, por volta de 1642, quando Pascal desenvolveu a Pascalina, uma m&aacute;quina de c&aacute;lculo que era &ldquo;autom&aacute;tica&rdquo; sem a necessidade de mover todas v&aacute;rias pe&ccedil;as e sim movendo apenas uma manivela. Ela consistia em um sistema de engrenagens, que a cada volta completa girava uma outra engrenagem, estas engrenagens assim com a soma no final armazenavam o resultado. Era um conceito bem b&aacute;sico, olhando nos dias atuais, mas na &eacute;poca que foi desenvolvida demonstrou um feito e grande, apesar de resolver problemas bem b&aacute;sicos de soma e subtra&ccedil;&atilde;o, sendo r&aacute;pida mas sendo bem espec&iacute;fica.</strong></p>
<p><strong>Outras m&aacute;quinas com a mesma tem&aacute;tica foram criadas usando engrenagens para c&aacute;lculos. Um dos grandes exemplos se teve&nbsp; de Leibniz, Babbage entre outros, e essas ferramentas tiveram import&acirc;ncia de modo que tornou cada vez mais eficiente a forma de calcular.</strong></p>
<p><strong>Agora tendo ideia de onde a humanidade estava olhando, podemos ver quais passos foram importantes, uma vez que sempre procurou aperfei&ccedil;oar os c&aacute;lculos, fazendo eles mais f&aacute;ceis e mais r&aacute;pidos de se realizar. Como a m&aacute;quina de Leibniz que resolveu o problema de divis&atilde;o e multiplica&ccedil;&atilde;o que era tido nas m&aacute;quinas Pascalinas, a quest&atilde;o agora era fazer com n&uacute;meros maiores e de forma mais r&aacute;pida e eficiente</strong></p>
<p>&nbsp;</p>
<h2>Maquina de Tear, o Primeiro Computador</h2>
<img className="m-4" src="https://cdn.shopify.com/s/files/1/0380/5913/files/card-maker.jpg?v=1613917142" alt="jacquard machine img" />
<p><strong>Esse &eacute; um dos componentes bem diferentes dentro desse tema, n&atilde;o &eacute; uma m&aacute;quina de somar e n&atilde;o foi feito com tema de computa&ccedil;&atilde;o ou coisa do tipo mas ainda &eacute; considerado por muitos o primeiro computador.&nbsp;</strong></p>
<p><strong>A m&aacute;quina de tear de Jacquard &eacute; algo revolucion&aacute;rio, n&atilde;o apenas por ter facilitado na cria&ccedil;&atilde;o de tecidos, mas na &aacute;rea de programa&ccedil;&atilde;o, uma vez que permitia a entrada de cart&otilde;es perfurados previamente para que fossem criados padr&otilde;es de tecelagem.</strong></p>
<p><strong>Antes da m&aacute;quina de tear existir todos os tecidos eram feitos a m&atilde;o, seja pela fia&ccedil;&atilde;o ou a tecelagem, um processo bem demorado e cuidadoso, ela resultou do mesmo elemento do &aacute;baco, surgiu em resposta da necessidade humana de realizar as coisas de forma mais eficiente e forma mais f&aacute;cil.</strong></p>
<img className="w-72 m-6" src="https://1drv.ms/i/c/ccdb940572a31808/IQQEzIWTA4lpS6YXDXFbj9bCAYCvLYqATogJQoLl0eqAxns" alt="" />
<p><strong>Como o ser humano sempre quer criar ferramentas para agilizar, melhorar ou aumentar a efici&ecirc;ncia do seu trabalho, o jacquard criou a m&aacute;quina de tear, com o intuito de aumentar a produ&ccedil;&atilde;o de tecidos.</strong></p>
<p><strong>O que realmente foi inovador e que contribuiu foi o Cart&atilde;o perfurado e o sistema que utilizava ele, foi um grande marco, sendo um item bem simples, mas que podia revelar grandes coisas, por exemplo:</strong></p>
<p><strong>O cart&atilde;o previamente perfurado era inserido nas m&aacute;quinas de Jacquard, n&atilde;o era apenas um cart&atilde;o, era uma corrente de cart&otilde;es, onde passavam pela m&aacute;quina.</strong></p>
<img className="w-72 m-6" src="https://1drv.ms/i/c/ccdb940572a31808/IQSqfzmmWY4pTZkX2u4gLNXkASZa3983pLNWbUlWqTuj3rU" alt="" />
<p><strong>Os furos indicavam quando os &ldquo;handlers&rdquo; ou ganchos puxavam as linhas</strong></p>
<p><strong>Quando um gancho entrava no buraco do cart&atilde;o, ele levantava</strong></p>
<img className="w-72 m-6" src="https://1drv.ms/i/c/ccdb940572a31808/IQQ4tGguvhcQRZLInFeMnJHzAa4c8EJe0ZBsYT9SGsRV9iE" alt="" />
<p><strong>E assim levantava tamb&eacute;m a linha, o que permitia selecionar quais linhas mudariam, sem que fosse feito manualmente.</strong></p>
<p><strong>Era um sistema b&aacute;sico de sim ou n&atilde;o, sim quando existia furo e gancho e n&atilde;o quando n&atilde;o havia nenhum dos dois, um sistema b&aacute;sico para o que futuramente se conheceria como sistema bin&aacute;rio.</strong></p>
<p><strong>Esse sistema foi muito importante, uma verdadeira maravilha da engenharia, digna de uma mente brilhante.</strong></p>
<p><strong>Esse sistema de mover as cordas j&aacute; era usado na tecelagem, entretanto de forma manual, era necess&aacute;rio levantar as cordas que voc&ecirc; desejava&nbsp; e assim controlar o desenho que voc&ecirc; queria.</strong></p>
<p><strong>A m&aacute;quina de Jacquard n&atilde;o foi importante apenas para a tecelagem, mas tamb&eacute;m para a computa&ccedil;&atilde;o demonstrando o pref&aacute;cio do conceito bin&aacute;rio que se tornaria pe&ccedil;a fundamental n&atilde;o somente no mundo da computa&ccedil;&atilde;o, mas de toda &aacute;rea eletr&ocirc;nica.</strong></p>
<p><a href="https://youtu.be/pzYucg3Tmho?si=cxf6wsJqLppyU0Gp"><strong>https://youtu.be/pzYucg3Tmho?si=cxf6wsJqLppyU0Gp</strong></a><strong>&nbsp;</strong></p>
<p><strong>Charles Babbagem e a Maquina Analitica</strong></p>
<img  src="https://community.cadence.com/resized-image/__size/640x0/__key/communityserver-blogs-components-weblogfiles/00-00-00-01-06/8132.diffeng.jpg" alt="" />
<p><strong>A m&aacute;quina de babbage foi um dos grandes passos para se entender at&eacute; ent&atilde;o o que se era poss&iacute;vel criar, at&eacute; agora apesar de todas as m&aacute;quinas serem consideradas &ldquo;computadores&rdquo; s&atilde;o na verdade imensas calculadoras ou m&aacute;quinas de tecelagem, at&eacute; ent&atilde;o feita em torno de 1837 antes mesmo de Thomas edison nascer n&atilde;o teria um resqu&iacute;cio de eletricidade a maquina analitica de babbage funcionava atraves de engrenagens, rodas, eixos e tudo que poderia se pensar, era uma m&aacute;quina &ldquo;autom&aacute;tica&rdquo; que poderia fazer c&aacute;lculos com precis&atilde;o de 50 casas decimais, um avan&ccedil;o tecnol&oacute;gico gigantesco.</strong></p>
<p><strong>Mas at&eacute; agora n&atilde;o tem nada que referencia ao computador voc&ecirc; deve estar pensando, mas aqui vem a parte boa.</strong></p>
<p><strong>A m&aacute;quina de babbage recebia os n&uacute;meros para calcular atrav&eacute;s de cart&otilde;es perfurados, uma das heran&ccedil;as que a m&aacute;quina de Jacquard contribuiu, eram atrav&eacute;s deles que a m&aacute;quina fazia seus c&aacute;lculos, o que fazia que n&atilde;o fosse necess&aacute;rio inserir um a um e sim v&aacute;rios de uma &uacute;nica vez, e n&atilde;o somente isso, a m&aacute;quina tamb&eacute;m imprimia o resultado.</strong></p>
<p><strong>Um avan&ccedil;o imenso se pensar no mundo at&eacute; essa &eacute;poca, pulou-se de um abaco a milhares de anos a uma m&aacute;quina de mais de 15 toneladas que realizava c&aacute;lculos sozinhos e ainda imprimia.</strong></p>
<p><strong>Apesar de ser muito eficiente e r&aacute;pida, a m&aacute;quina de babbage ainda era bem cara de se fazer e reproduzir, era composta&nbsp; de 8.000 a 10.000 pe&ccedil;as, uma coisa que para reproduzir demora tempos e tempos.</strong></p>
<p><strong>na era da eletricidade</strong></p>
<p><strong>Agora com o uso da eletricidade em uma escala muito grande, &eacute; de se pensar que os inventores agora passariam a usar ela em suas inven&ccedil;&otilde;es, e hoje &eacute; dif&iacute;cil pensar em coisas tecnologias sem eletricidade</strong></p>
<p><strong>Hollerith e a m&aacute;quina de tabula&ccedil;&atilde;o</strong></p>
<img className="w-72 m-6" src="https://time.graphics/uploadedFiles/500/de/94/de9438cab9d57588aa41cee6b53402a4.jpg" alt="" />
<p><strong>Uma m&aacute;quina que se utilizava da mesma tecnologia dos cart&otilde;es perfurados,&nbsp; mas agora com energia, a m&aacute;quina de Hollerith podia calcular grandes quantidades de dados armazenados nos cart&otilde;es perfurados, usando uma tecnologia bem&nbsp; simples.</strong></p>
<p><strong>&nbsp;Vamos usar o mesmo exemplo do tear.</strong></p>
<p><strong>Agora com cart&otilde;es de papel, simples e perfurados, usava-se pinos met&aacute;licos com energia, cada pino que passava dentro dos buracos do cart&atilde;o e encontrava um &ldquo;circuito&rdquo; que fazia com que pudesse ler.</strong></p>
<p><strong>Cada furo correspondia a uma resposta, e a posi&ccedil;&atilde;o exata no cart&atilde;o indicava o campo a que aquela resposta pertencia, utilizava do modelo do tear de Jacquard, mas Hollerith levou isso a outro n&iacute;vel ao integr&aacute;-lo com a eletricidade.</strong></p>
<p><strong>O funcionamento da m&aacute;quina de Hollerith era engenhoso. Os cart&otilde;es perfurados eram inseridos em uma esp&eacute;cie de leitor que possu&iacute;a uma matriz de pinos met&aacute;licos m&oacute;veis. Quando o pino encontrava um furo no cart&atilde;o, ele passava por esse buraco e tocava uma placa de contato met&aacute;lica abaixo. Essa conex&atilde;o permitia que a corrente el&eacute;trica flu&iacute;sse pelo circuito e fosse registrada. Ou seja, cada furo permitia o fechamento de um circuito el&eacute;trico, e esse pulso era ent&atilde;o contado por rel&eacute;s eletromec&acirc;nicos, que registravam o dado correspondente.</strong></p>
<p><strong>Cada campo perfurado podia acionar um contador mec&acirc;nico separado, permitindo que os dados fossem automaticamente agregados &agrave; medida que os cart&otilde;es eram processados. Assim, a m&aacute;quina n&atilde;o apenas lia, mas tamb&eacute;m contava e organizava informa&ccedil;&otilde;es estat&iacute;sticas em tempo real, algo totalmente inovador para a &eacute;poca. A m&aacute;quina pode apresentar ideias novas utilizando os mesmo conceitos b&aacute;sicos da m&aacute;quina Pascalina e da m&aacute;quina de tear, agora evolu&iacute;dos a uma era muito mais mudada.</strong></p>
<p><strong>&nbsp;</strong></p>
<p><strong>&nbsp;1835</strong></p>
<p><strong>Rel&eacute;s</strong></p>
<p><strong>Um interruptor ativado eletricamente ele tem grande impacto na era pr&eacute; computadores, de forma que foi o in&iacute;cio para a cria&ccedil;&atilde;o de circuitos e outras pe&ccedil;as de grande import&acirc;ncia futura.</strong></p>
<p><strong>O funcionamento do rel&eacute; &eacute; at&eacute; bem f&aacute;cil de compreender</strong></p>
<img className="w-72 m-6" src="https://1drv.ms/i/c/ccdb940572a31808/IQRcEryoFmQzR52fgIdmnXv8AaJsB8EsJvVyTZUEKSqOn2A" alt="" />
<p><strong>Com o uso da eletricidade ascendendo se teve grandes descobertas, uma das mais importantes &eacute; a de que se voc&ecirc; energizar um fio de cobre se &eacute; criado um campo eletromagn&eacute;tico, mais conhecido como im&atilde;.</strong></p>
<p><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong> <strong>Isso foi importante de tal maneira, que agora se poderia criar im&atilde;s apenas energizando fios de cobre.</strong></p>
<p><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong> <strong>O rel&eacute; se aproveita dessa descoberta.</strong></p>
<p><strong>Em amarelo temos um rolo de fio de cobre, quando a energia &eacute; passada por ele &eacute; criado um campo eletromagn&eacute;tico tornando-o um im&atilde;, o que atrai o metal acima dele.&nbsp; &nbsp; &nbsp; </strong></p>
<p><strong>Agora&nbsp; o &iacute;m&atilde;&nbsp; puxa a haste de metal acima dele, no outro lado do circuito ele pode ativar uma linha fragmentada de eletricidade, transformando em uma linha cont&iacute;nua, um &oacute;timo exemplo de como ligar e desligar uma l&acirc;mpada.</strong></p>
<img className="w-72 m-6" src="https://1drv.ms/i/c/ccdb940572a31808/IQRoqTenI-ZXSqcRSIf1euazAf3KWN-1hH23VLVMCOKvCyo" alt="" />
<p><strong>Esse sistema foi muito importante uma vez que fazia com que pudesse ser controlado equipamentos e n&atilde;o us&aacute;-los apenas com um circuito &uacute;nico, esse sistema por ser observado como um sistema bin&aacute;rio, uma vez que pode ser usados tanto como ligado ou desligado, h&aacute; outros tipos de rel&eacute; que funciona de formas contr&aacute;rias, ele quando ativado ao inv&eacute;s de ligar, desligar uma corrente cont&iacute;nua.</strong></p>
<p><strong>Os rel&eacute; foram muito usados no in&iacute;cio da era da comunica&ccedil;&atilde;o, quando o r&aacute;dio foi criado, os rel&eacute;s eram usados para ampliar o seu sinal, mas depois descobriram que poderiam criar uma s&eacute;rie de ondas de pulsos el&eacute;tricos com ele e ent&atilde;o descobriram o seu uso na &aacute;rea da computa&ccedil;&atilde;o.</strong></p>
<p><strong>Com o in&iacute;cio da era da Eletricidade de Thomas Edison, as l&acirc;mpadas tamb&eacute;m se tornaram um elemento crucial, uma fonte de luz a base de energia que encantou milh&otilde;es de pessoas e que at&eacute; hoje &eacute; de grande import&acirc;ncia e&nbsp; impacto nos computadores, mas n&atilde;o as l&acirc;mpadas comuns, mas sim uma varia&ccedil;&atilde;o.</strong></p>
<p><strong>Os tubos de v&aacute;cuo</strong></p>
<p><strong>Como uma l&acirc;mpada inicialmente funciona?</strong></p>
<p><strong>Uma inven&ccedil;&atilde;o que mudou completamente a humanidade tem uma f&iacute;sica bem simples por tr&aacute;s da sua forma de funcionamento.</strong></p>
<p><strong>&nbsp;</strong></p>
<img className="w-72 m-6" src="https://upload.wikimedia.org/wikipedia/commons/6/65/Triode_vacuum_tube.png" alt="" />
<p><strong>Uma l&acirc;mpada &eacute; composta por um tubo de vidro&nbsp; a v&aacute;cuo ou com g&aacute;s que em seu interior tem um filamento de tungst&ecirc;nio e um suporte que conecta o tungst&ecirc;nio &agrave; eletricidade.</strong></p>
<p><strong>O funcionamento da l&acirc;mpada se d&aacute; a rea&ccedil;&atilde;o do filamento ao receber energia, por ser um fio fino demais ao ser energizado ele aquece e ao ser aquecido cada vez mais ele libera calor que &eacute; visto em forma de luz, o tubo de vidro serve para evitar que o oxig&ecirc;nio chegue ao tungst&ecirc;nio, uma vez que o oxig&ecirc;nio degrada o filamento quando ligado.</strong></p>
<p><strong>Os tubos de v&aacute;cuo surgiram como uma modifica&ccedil;&atilde;o das lampadas, inicialmente foi notado que se voc&ecirc; adicionasse a l&acirc;mpada mais um filamento agora uma placa de metal, quando criar esse sistema puderam ver que quando&nbsp; a placa de metal erra positivamente carregada ela atrai el&eacute;trons e quando era negativamente, afastava os el&eacute;trons.</strong></p>
<p><strong>Com isso perceberam que podia tornar de forma rudimentar energia cont&iacute;nua em energia alternada, mas o grande avan&ccedil;o mesmo veio com o triodo</strong></p>
<p><strong>Adicionado uma nova grade entre os filamentos, na qual eram suprimidos diferentes tipos de cargas, se notou que era um excelente amplificador.</strong></p>
<p><strong>Esse novo amplificador foi um item revolucion&aacute;rio, uma vez que agora fazia com que as chamadas, as ondas de r&aacute;dios e outros itens pudesse agora chegar a qualquer parte do pa&iacute;s.</strong></p>
<p><strong>Usado agora em larga escala em tudo aquilo que se queria alterar a corrente, tudo que se queria ampliar o sinal se tornou um componente eletr&ocirc;nico importante.</strong></p>
<p><strong>O computador de stibitz - O primeiro computador a usar o sistema bin&aacute;rio</strong></p>
<img className="w-72 m-6" src="https://cdn.sanity.io/images/r000fwn3/production/4bfd9b02811b6242ac530226c8db705d5518ea14-1280x773.jpg?w=450" alt="" />
<p><strong>O sistema booleano &eacute; uma jun&ccedil;&atilde;o da filosofia l&oacute;gica com a matem&aacute;tica, desenvolvida por claude Shannon, vou explicar:</strong></p>
<p><strong>considere sim quando &eacute; verdadeiro um ato</strong></p>
<p><strong>e n&atilde;o quando &eacute; falso.</strong></p>
<p><strong>Considera que voce tem quatro sequ&ecirc;ncias:</strong></p>
<p><strong>Sim e Sim, a resposta &eacute; verdadeira se as duas senten&ccedil;as forem verdadeiras</strong></p>
<p><strong>Sim e N&atilde;o, a resposta &eacute; falsa&nbsp; se uma for falsa</strong></p>
<p><strong>N&atilde;o e Sim a resposta &eacute; falsa se uma for falsa</strong></p>
<p><strong>N&atilde;o e N&atilde;o, a resposta &eacute; falsa se as duas senten&ccedil;as foram falsas</strong></p>
<p><strong>A m&aacute;quina de stibitz funcionava dessa maneira, usando a soma.</strong></p>
<p><strong>Quando apenas um lado est&aacute; sendo pressionado, a l&acirc;mpada correspondente a 1 era acesa, independentemente de qual dos lados fosse pressionado, quando nenhum dos lados fossem pressionados significava que nenhuma l&acirc;mpada era acesa, e se os dois lados fossem pressionado juntos a luz de n&uacute;mero 2 era acesse, aqui nasceu o princ&iacute;pio da soma com ferramentas eletr&ocirc;nicas;</strong></p>
<p><strong>Isso era poss&iacute;vel porque stibitz criou um sistema baseado no mesmo&nbsp; &ldquo;e&rdquo; do exemplo assim, onde s&oacute; se era verdadeiro (acender a l&acirc;mpada 2) quando as duas op&ccedil;&otilde;es fossem verdadeiras (quando os dois lados fossem pressionados)</strong></p>
<p><strong>Atanasoff computer</strong></p>
<p><strong>Ao contr&aacute;rio de todas as m&aacute;quinas anteriores, esse n&atilde;o era movido por engrenagens ou mecanismos manuais, mas sim com elementos el&eacute;tricos, sendo&nbsp; uma nova forma de se criar m&aacute;quinas, funcionam com base em tubos de v&aacute;cuo j&aacute; explicados, que permitiam o controle da passagem de eletricidade em um circuito, um verdadeiro &ldquo;sim&rdquo; ou &ldquo;n&atilde;o&rdquo; eletr&ocirc;nico.</strong></p>
<p><strong>Foi adotado o sistema bin&aacute;rio como base de seus c&aacute;lculos, utilizando 0 e 1 para representar qualquer valor. Isso foi uma ruptura com os sistemas decimais anteriores. Para armazenar temporariamente os dados, ele usava capacitores, que guardavam pequenas cargas el&eacute;tricas por um curto per&iacute;odo. Como esses capacitores perdiam a carga com o tempo, era necess&aacute;rio que os dados fossem constantemente &ldquo;regravados&rdquo;, um m&eacute;todo chamado de mem&oacute;ria regenerativa.</strong></p>
<p><strong>&nbsp;</strong></p>
<p><strong>ENIAC &ndash; 1946</strong></p>
<img className="w-72 m-6" src="https://admin.cnnbrasil.com.br/wp-content/uploads/sites/12/2021/06/26776_1798DEE935286D54.jpg" alt="" />
<p><strong>Um gigante tecnol&oacute;gico que carregava consigo a ess&ecirc;ncia do que viria a ser o computador moderno.&nbsp; Se utilizando de todas as inven&ccedil;&otilde;es anteriores criou uma m&aacute;quina colossal, com mais de 18.000 tubos de v&aacute;cuo, ocupando uma sala inteira e consumindo uma enorme quantidade de energia. Ainda assim, era milhares de vezes mais r&aacute;pido que qualquer m&aacute;quina anterior.</strong></p>
<p><strong>Seu funcionamento era inteiramente eletr&ocirc;nico, e ele j&aacute; conseguia executar instru&ccedil;&otilde;es sequenciais como soma, subtra&ccedil;&atilde;o, multiplica&ccedil;&atilde;o e divis&atilde;o. No entanto, ele ainda n&atilde;o possu&iacute;a um sistema de mem&oacute;ria program&aacute;vel. Para mudar a fun&ccedil;&atilde;o que o ENIAC realizava, era necess&aacute;rio reconectar cabos f&iacute;sicos e reposicionar chaves manuais, como uma central telef&ocirc;nica. Isso significa que ele era extremamente poderoso, mas pouco flex&iacute;vel.</strong></p>
<p><strong>Mesmo com essa limita&ccedil;&atilde;o, o ENIAC provou que era poss&iacute;vel realizar c&aacute;lculos gerais de forma autom&aacute;tica, e que m&aacute;quinas podiam ser adaptadas para diferentes fun&ccedil;&otilde;es computacionais. Foi um divisor de &aacute;guas na hist&oacute;ria da tecnologia.</strong></p>
<p><strong>Cada tubo de v&aacute;cuo representava um estado: ligado (1) ou desligado (0). A eletricidade n&atilde;o girava engrenagens nem movia pe&ccedil;as mec&acirc;nicas como nas m&aacute;quinas de Babbage, agora aproveitando da nova revolu&ccedil;&atilde;o criada pelo uso de eletricidade e ent&atilde;o se pode ver milhares de circuitos interligados, uma breve introdu&ccedil;&atilde;o do que se tornaria futuramente os processadores.</strong></p>
<p><strong>Era uma m&aacute;quina bem r&uacute;stica, mas que descrevia o que futuramentes se tornaria um computador comum, tinham partes como m&oacute;dulos para somadores, multiplicadores, divisores, conversores de n&uacute;meros decimais para bin&aacute;rios, e at&eacute; um painel de controle para orquestrar todas essas opera&ccedil;&otilde;es e a entrada de dados era feita por cart&otilde;es perfurados, e os resultados podiam ser enviados de volta aos cart&otilde;es ou exibidos por luzes e impressoras.</strong></p>
<p><strong>Mas seu verdadeiro diferencial estava na velocidade, enquanto uma calculadora mec&acirc;nica levava segundos para fazer uma multiplica&ccedil;&atilde;o, o ENIAC podia realizar cinco mil somas por segundo e uma multiplica&ccedil;&atilde;o a cada tr&ecirc;s milissegundos, um avan&ccedil;o gigantesco comparados ao que foram inventados at&eacute; o momento. Isso representava uma transforma&ccedil;&atilde;o brutal e at&eacute; est&atilde;o os problemas que antes levavam semanas para serem resolvidos agora podiam ser solucionados em horas ou at&eacute; minutos, um avan&ccedil;o sem igual.</strong></p>
<p><strong>Apesar de ser uma m&aacute;quina eletr&ocirc;nica, o ENIAC ainda n&atilde;o era um computador como conhecemos hoje, j&aacute; que ele n&atilde;o armazena programas em mem&oacute;ria. Para mudar a tarefa que o ENIAC realizava, era necess&aacute;rio program&aacute;-lo manualmente, o que significava reconectar cabos f&iacute;sicos entre seus m&oacute;dulos de c&aacute;lculo e ajustar interruptores em grandes pain&eacute;is de controle, sendo assim uma tarefa bem trabalhosa. Cada novo problema exigia quase uma &ldquo;reconstru&ccedil;&atilde;o&rdquo; do caminho l&oacute;gico da m&aacute;quina, um processo que podia levar dias.</strong></p>
<p><strong>No entanto, o ENIAC j&aacute; era totalmente autom&aacute;tico e uma vez configurado, ele seguia a sequ&ecirc;ncia de opera&ccedil;&otilde;es sem interven&ccedil;&atilde;o humana, o que por si s&oacute; era uma revolu&ccedil;&atilde;o. Ele j&aacute; possu&iacute;a uma esp&eacute;cie de &ldquo;unidade de controle&rdquo; que determinava a ordem das opera&ccedil;&otilde;es, e trabalhava com n&uacute;meros armazenados em registradores eletr&ocirc;nicos, o que o tornava capaz de manter valores em mem&oacute;ria durante os c&aacute;lculos, algo imposs&iacute;vel nas calculadoras anteriores, uma ideia da reutiliza&ccedil;&atilde;o de valores para c&aacute;lculos p&oacute;stumos.</strong></p>
<p><strong>Por mais primitivo que o processo de reprograma&ccedil;&atilde;o do ENIAC possa parecer hoje, ele abriu portas para o pr&oacute;ximo passo que se tornaria o conceito de programa armazenado na mem&oacute;ria, que viria com a arquitetura de von Neumann..</strong></p>
<p><strong>O ENIAC mostrou que a eletricidade podia pensar, e que os c&aacute;lculos mais complexos podiam ser resolvidos n&atilde;o por l&aacute;pis e papel, mas por luzes piscando em um painel met&aacute;lico, movidas pela l&oacute;gica de 0s e 1. Foi a primeira vez na hist&oacute;ria em que o homem construiu uma mente el&eacute;trica, e abriu o caminho para tudo que viria depois, desde celulares a intelig&ecirc;ncia artificial.</strong></p>
<p><strong>Von Neumann</strong></p>
<p><strong>Ap&oacute;s o sucesso do ENIAC, os engenheiros e matem&aacute;ticos da &eacute;poca perceberam que era preciso algo mais para os computadores e era uma forma de tornar os computadores program&aacute;veis de maneira flex&iacute;vel, sem a necessidade de reconectar fios e circuitos toda vez que uma nova tarefa fosse atribu&iacute;da. A resposta veio com uma ideia simples, mas revolucion&aacute;ria, proposta por John von Neumann era de&nbsp; armazenar tanto os dados quanto as instru&ccedil;&otilde;es na mesma mem&oacute;ria, como se fossem apenas n&uacute;meros a serem manipulados.</strong></p>
<p><strong>Mas isso gerou um novo problema que era: como construir essa mem&oacute;ria? Onde guardar os dados e os programas que deveriam ser lidos, interpretados e executados automaticamente pela m&aacute;quina? Eu te digo, os tubos de von Neumann.</strong></p>
<p><strong>Esse tubo mostrava pontos de carga que representavam bits, a ideia era simples e brilhante: de forma bem rudimentar, o tubo funcionava como uma mini Tv, a cada resposta&nbsp; o tubo inseria na tela da tv dava um resultado.</strong></p>
<p>&nbsp;</p>
<p><strong>Assim, pela primeira vez, um computador podia armazenar diretamente na eletr&ocirc;nica interna tanto os dados a serem manipulados quanto o pr&oacute;prio programa que dizia o que fazer com esses dados. O tubo permite leitura e escrita eletr&ocirc;nica de informa&ccedil;&otilde;es bin&aacute;rias com alta velocidade, abrindo as portas para a cria&ccedil;&atilde;o de sistemas program&aacute;veis por software, sem qualquer interven&ccedil;&atilde;o f&iacute;sica no hardware.</strong></p>
<p><strong>Mas como os capacitores do ABC, os tubos de von Neumann tamb&eacute;m tinham suas fragilidades. A carga el&eacute;trica nos pontos da tela n&atilde;o durava para sempre: ap&oacute;s alguns segundos ela come&ccedil;ava a se dissipar. Por isso, era necess&aacute;rio um sistema de regenera&ccedil;&atilde;o cont&iacute;nua, o computador lia os dados antes que se apagassem e os escrevia no mesmo lugar. Era uma mem&oacute;ria vol&aacute;til e din&acirc;mica, que precisava ser constantemente mantida viva, o ancestral direto da mem&oacute;ria DRAM que usamos hoje.</strong></p>
<p><strong>Os tubos n&atilde;o duraram muito tempo como padr&atilde;o industrial, pois eram caros, fr&aacute;geis e sens&iacute;veis a interfer&ecirc;ncia. Ainda assim, foram cruciais para a primeira gera&ccedil;&atilde;o de computadores baseados na arquitetura de von Neumann, como o EDVAC, o Manchester Baby e o IAS Machine. Foram a primeira implementa&ccedil;&atilde;o real do conceito de programa armazenado, e mostraram que a mem&oacute;ria podia ser constru&iacute;da com luz, carga el&eacute;trica e l&oacute;gica pura, sem engrenagens, cart&otilde;es ou papel.</strong></p>
<p><strong>Enquanto hoje mem&oacute;rias ocupam espa&ccedil;os microsc&oacute;picos dentro de chips de sil&iacute;cio, os tubos de von Neumann lembram uma era em que cada bit precisava ser fisicamente vis&iacute;vel, mantido com cuidado e reconstru&iacute;do com precis&atilde;o. Foram um passo fundamental na transforma&ccedil;&atilde;o do computador em uma m&aacute;quina realmente inteligente ,capaz de lembrar, decidir e executar sem ajuda humana, seguindo apenas as instru&ccedil;&otilde;es de um programa invis&iacute;vel, armazenado como fa&iacute;scas numa tela de vidro.</strong></p>
<p><strong>Transistores &ndash; o fim dos tubos e o come&ccedil;o da miniaturiza&ccedil;&atilde;o</strong></p>
<p><strong>Enquanto as mem&oacute;rias evolu&iacute;am, o processamento tamb&eacute;m precisava mudar. Os tubos de v&aacute;cuo, usados em larga escala no ENIAC e mesmo nos computadores de von Neumann, sofriam de um problema cr&ocirc;nico: eram fr&aacute;geis, esquentavam demais, queimavam com facilidade e ocupavam muito espa&ccedil;o.</strong></p>
<p><strong>Em 1947, os laborat&oacute;rios Bell anunciaram uma inven&ccedil;&atilde;o que mudaria tudo: o transistor. Um pequeno componente feito de material semicondutor como&nbsp; sil&iacute;cio, capaz de amplificar sinais el&eacute;tricos ou funcionar como interruptor eletr&ocirc;nico, substituindo com efici&ecirc;ncia um tubo de v&aacute;cuo.</strong></p>
<p><strong>O transistor tinha tudo o que os engenheiros desejavam: era menor, mais barato, mais r&aacute;pido, n&atilde;o quebrava com facilidade e consumia muito menos energia. Isso permitiu a constru&ccedil;&atilde;o de computadores menores, mais confi&aacute;veis e com muito mais capacidade. Era o in&iacute;cio da segunda gera&ccedil;&atilde;o da computa&ccedil;&atilde;o.</strong></p>
<p><strong>A arquitetura interna dos computadores permaneceu a mesma, com mem&oacute;ria, unidade de controle, ULA e dispositivos de entrada e sa&iacute;da, mas agora tudo era transistorizado, abrindo caminho para a pr&oacute;xima grande revolu&ccedil;&atilde;o.</strong></p>
<p>Bom, para finalizar espero que tenha aproveitado, se contém imprecisões, erros de gramáticas ou outros, comente abaixo.</p>
</div>

      <Comments comments={0} {...props} />
    </>
  );
}

export default PrimeirosCOmputadores;